# Generated by Django 4.2.7 on 2023-11-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_city', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('reserved', models.BooleanField(default=False, null=True)),
                ('sold', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
